# Generated by Django 5.2.7 on 2025-12-28 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bank_name'],
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=200)),
                ('gst_no', models.CharField(blank=True, help_text='GST Number (e.g., 22AAAAA0000A1Z5)', max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN Number (e.g., AAAAA0000A)', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Full company address', null=True)),
                ('email', models.EmailField(blank=True, help_text='Company email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Company phone number', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='company/logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Detail',
                'verbose_name_plural': 'Company Details',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Lower number = earlier in approval chain', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active levels require approval')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vouchers.designation')),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FunctionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('function_date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('function_name', models.CharField(max_length=200)),
                ('booked_by', models.CharField(help_text='Name of person/company who booked', max_length=200)),
                ('contact_numbers', models.JSONField(default=list, help_text='List of contact numbers')),
                ('address', models.TextField(max_length=500)),
                ('menu_items', models.JSONField(default=dict, help_text='Menu items categorized: {welcome_drink, starters, main_course, desserts}')),
                ('no_of_pax', models.IntegerField()),
                ('rate_per_pax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_option', models.CharField(choices=[('INCLUDING', 'Including GST'), ('EXCLUDING', 'Excluding GST')], default='INCLUDING', max_length=20)),
                ('hall_rent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('location', models.CharField(choices=[('Banquet', 'Banquet'), ('Restaurant', 'Restaurant'), ('Family Room', 'Family Room'), ('Outdoor', 'Outdoor')], help_text='Location where the function will be held', max_length=50)),
                ('extra_charges', models.JSONField(default=list, help_text='List of extra charges with description and rate')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining amount to be paid (Total - Advance)', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Function Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Function confirmation status', max_length=20)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Advance payment amount', max_digits=12, null=True)),
                ('food_pickup_time', models.TimeField(blank=True, help_text='Time when food should be picked up', null=True)),
                ('food_service_time', models.TimeField(blank=True, help_text='Time when food service should begin', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions or notes for the function', null=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Marked as Completed')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when function was confirmed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='User who confirmed the function', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_functions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticularAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/particulars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vouchers.particular')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_voucher', models.BooleanField(default=True, help_text='User can create new vouchers')),
                ('can_edit_voucher', models.BooleanField(default=False, help_text='User can edit existing vouchers (only accountants, only pending, only if no approvals yet)')),
                ('can_view_voucher_list', models.BooleanField(default=True, help_text='User can view voucher list page')),
                ('can_view_voucher_detail', models.BooleanField(default=True, help_text='User can view individual voucher details')),
                ('can_print_voucher', models.BooleanField(default=True, help_text='User can print vouchers')),
                ('can_create_function', models.BooleanField(default=True, help_text='User can create new function bookings')),
                ('can_edit_function', models.BooleanField(default=False, help_text='User can edit existing function bookings')),
                ('can_delete_function', models.BooleanField(default=False, help_text='User can delete function bookings')),
                ('can_view_function_list', models.BooleanField(default=True, help_text='User can view function calendar/list page')),
                ('can_view_function_detail', models.BooleanField(default=True, help_text='User can view individual function details')),
                ('can_print_function', models.BooleanField(default=True, help_text='User can print function prospectus')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, help_text='Mobile number (e.g., +91 9876543210 or 9876543210)', max_length=15, null=True)),
                ('signature', models.ImageField(blank=True, help_text='Upload your digital signature (PNG/JPG, transparent background recommended)', null=True, upload_to='signatures/')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('voucher_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('PETTY_CASH', 'Petty Cash')], max_length=20)),
                ('name_title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=5)),
                ('pay_to', models.CharField(max_length=200)),
                ('cheque_number', models.CharField(blank=True, help_text='Required only for Cheque payments', max_length=20, null=True)),
                ('cheque_date', models.DateField(blank=True, help_text='Date on the cheque - required for Cheque payments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('required_approvers_snapshot', models.JSONField(blank=True, default=list, help_text='List of usernames required at voucher creation time')),
                ('account_details', models.ForeignKey(blank=True, help_text='Bank account for Cheque payments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.accountdetail')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='particular',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='vouchers.voucher'),
        ),
        migrations.CreateModel(
            name='MainAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/main/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_attachments', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/cheques/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_attachments', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when status is REJECTED', null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='vouchers.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'approver')},
            },
        ),
    ]
