# Generated by Django 5.2.7 on 2025-12-11 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='functionbooking',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advance payment amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when function was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='User who confirmed the function', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_functions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Function Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Function confirmation status', max_length=20),
        ),
    ]
