# Generated by Django 5.2.7 on 2025-12-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_functionbooking_advance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionbooking',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='contact_numbers',
            field=models.JSONField(default=list, help_text='List of contact numbers'),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='extra_charges',
            field=models.JSONField(default=list, help_text='List of extra charges with description and rate'),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='gst_option',
            field=models.CharField(choices=[('INCLUDING', 'Including GST'), ('EXCLUDING', 'Excluding GST')], default='INCLUDING', max_length=20),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='hall_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='menu_items',
            field=models.JSONField(default=list, help_text='List of menu items'),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='rate_per_pax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
