# Generated by Django 5.2.7 on 2026-01-06 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_create_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetail',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AddField(
            model_name='companydetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set as active company (only one can be active at a time)'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='company/logos/'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
