# Generated by Django 5.2.7 on 2025-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_remove_functionbooking_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionbooking',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining amount to be paid (Total - Advance)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='location',
            field=models.CharField(blank=True, choices=[('Banquet', 'Banquet'), ('Restaurant', 'Restaurant'), ('Family Room', 'Family Room'), ('Outdoor', 'Outdoor')], help_text='Location where the function will be held', max_length=50, null=True),
        ),
    ]
