# Generated by Django 5.2.7 on 2026-01-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_companydetail_options_companydetail_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetail',
            options={'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='company/logo/'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
