# Generated by Django 5.2.7 on 2025-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_functionbooking_due_amount_functionbooking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionbooking',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special instructions or notes for the function', null=True),
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='location',
            field=models.CharField(choices=[('Banquet', 'Banquet'), ('Restaurant', 'Restaurant'), ('Family Room', 'Family Room'), ('Outdoor', 'Outdoor')], default=12, help_text='Location where the function will be held', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='menu_items',
            field=models.JSONField(default=dict, help_text='Menu items categorized: {welcome_drink, starters, main_course, desserts}'),
        ),
    ]
