# Generated by Django 5.2.7 on 2026-01-08 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_alter_companydetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetail',
            options={'ordering': ['name'], 'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this user belongs to', related_name='users', to='vouchers.companydetail'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='pan_no',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your digital signature', null=True, upload_to='signatures/'),
        ),
    ]
