# Generated by Django 5.2.7 on 2025-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_functionbooking_special_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionbooking',
            name='food_pickup_time',
            field=models.TimeField(blank=True, help_text='Time when food should be picked up', null=True),
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='food_service_time',
            field=models.TimeField(blank=True, help_text='Time when food service should begin', null=True),
        ),
    ]
