# Generated by Django 5.2.7 on 2026-01-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_alter_companydetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetail',
            options={'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='companies',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Number (e.g., 22AAAAA0000A1Z5)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='pan_no',
            field=models.CharField(blank=True, help_text='PAN Number (e.g., AAAAA0000A)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number (e.g., +91 9876543210 or 9876543210)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your digital signature (PNG/JPG, transparent background recommended)', null=True, upload_to='signatures/'),
        ),
    ]
