# Generated by Django 5.2.7 on 2026-01-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_alter_companydetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallevel',
            options={'ordering': ['company', 'order'], 'verbose_name': 'Approval Level', 'verbose_name_plural': 'Approval Levels'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.designation'),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='order',
            field=models.PositiveIntegerField(help_text='Lower number = earlier in approval chain'),
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='function_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_edit_voucher',
            field=models.BooleanField(default=False, help_text='User can edit existing vouchers'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=200, unique=True)),
                ('gst_no', models.CharField(blank=True, help_text='GST Number', max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN Number', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Full company address', null=True)),
                ('email', models.EmailField(blank=True, help_text='Company email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Company phone', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='company/logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Active companies appear in selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='accountdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='vouchers.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this approval level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='vouchers.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionbooking',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this function belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='vouchers.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermission',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company these permissions apply to', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='vouchers.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this voucher belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accountdetail',
            unique_together={('company', 'bank_name', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together={('company', 'designation')},
        ),
        migrations.AlterUniqueTogether(
            name='functionbooking',
            unique_together={('company', 'function_number')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('company', 'voucher_number')},
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Admin Staff', 'Admin Staff'), ('Accountants', 'Accountants')], help_text="User's role in this company", max_length=50)),
                ('mobile', models.CharField(blank=True, help_text='Mobile number for this company', max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memberships hide the company from user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='vouchers.company')),
                ('designation', models.ForeignKey(blank=True, help_text='Required for Admin Staff', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.designation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Membership',
                'verbose_name_plural': 'Company Memberships',
                'ordering': ['company__name', 'user__username'],
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
    ]
