# Generated by Django 5.2.7 on 2025-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_functionbooking_food_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number (e.g., +91 9876543210 or 9876543210)', max_length=15, null=True),
        ),
    ]
