# Generated by Django 5.2.7 on 2026-01-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_alter_approvallevel_options_alter_voucher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this designation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='vouchers.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('company', 'name')},
        ),
    ]
