# Generated by Django 5.2.7 on 2025-12-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_userprofile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionbooking',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Marked as Completed'),
        ),
    ]
