# Generated by Django 5.2.7 on 2026-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_alter_designation_options_designation_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='designation',
            name='company',
        ),
    ]
