# Generated by Django 5.2.7 on 2025-12-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_userpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
