# Generated by Django 5.2.7 on 2026-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_alter_designation_options_designation_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive accounts cannot be used in vouchers'),
        ),
    ]
