# Generated by Django 5.2.7 on 2025-12-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_userpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
