# Generated by Django 5.2.7 on 2026-01-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_accountdetail_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='is_active',
        ),
    ]
