# Generated by Django 5.2.7 on 2025-12-16 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_delete_userpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_voucher', models.BooleanField(default=True, help_text='User can create new vouchers')),
                ('can_edit_voucher', models.BooleanField(default=False, help_text='User can edit existing vouchers (only accountants, only pending, only if no approvals yet)')),
                ('can_create_function', models.BooleanField(default=True, help_text='User can create new function bookings')),
                ('can_edit_function', models.BooleanField(default=False, help_text='User can edit existing function bookings')),
                ('can_delete_function', models.BooleanField(default=False, help_text='User can delete function bookings')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
    ]
