# Generated by Django 5.2.7 on 2026-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_remove_accountdetail_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdetail',
            options={'ordering': ['-is_active', 'bank_name']},
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active accounts appear in voucher creation'),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
