# Generated by Django 5.2.7 on 2025-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0013_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_print_function',
            field=models.BooleanField(default=True, help_text='User can print function prospectus'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_print_voucher',
            field=models.BooleanField(default=True, help_text='User can print vouchers'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_view_function_detail',
            field=models.BooleanField(default=True, help_text='User can view individual function details'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_view_function_list',
            field=models.BooleanField(default=True, help_text='User can view function calendar/list page'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_view_voucher_detail',
            field=models.BooleanField(default=True, help_text='User can view individual voucher details'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_view_voucher_list',
            field=models.BooleanField(default=True, help_text='User can view voucher list page'),
        ),
    ]
