# Generated by Django 5.2.7 on 2026-01-14 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0013_alter_accountdetail_options_accountdetail_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionbooking',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Required for Admin Staff, N/A for Super Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.designation'),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='group',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin Staff', 'Admin Staff'), ('Accountants', 'Accountants')], help_text="User's role in this company", max_length=50),
        ),
    ]
