# Generated by Django 5.2.7 on 2026-04-16 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0015_alter_companymembership_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_functions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='food_pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='food_service_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functionbooking',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_create_function',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_create_voucher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_delete_function',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_edit_function',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_edit_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_print_function',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_print_voucher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view_function_detail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view_function_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view_voucher_detail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view_voucher_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='account_details',
            field=models.ForeignKey(blank=True, help_text='Bank account for Cheque / Online payments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.accountdetail'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('PETTY_CASH', 'Petty Cash'), ('ONLINE', 'Online')], max_length=20),
        ),
    ]
