# Generated by Django 5.2.7 on 2026-04-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0017_alter_functionbooking_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('PETTY_CASH', 'Petty Cash'), ('ONLINE', 'Online')], max_length=20),
        ),
    ]
