# Generated by Django 5.2.7 on 2026-04-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0018_alter_voucher_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='account_details',
            field=models.ForeignKey(blank=True, help_text='Bank account for Cheque/Online payments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.accountdetail'),
        ),
        migrations.CreateModel(
            name='OnlineAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/online/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_attachments', to='vouchers.voucher')),
            ],
        ),
    ]
