# Generated by Django 5.2.7 on 2026-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0021_vehicle_master_holiday_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaybooking',
            name='extra_km_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='holidaybooking',
            name='max_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaybooking',
            name='payment_type_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaybooking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaybooking',
            name='second_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='holidaybooking',
            name='destination',
            field=models.CharField(max_length=500),
        ),
    ]
