# Generated by Django 5.2.7 on 2026-06-02 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0023_holiday_batta_paymenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batta_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batta_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diesel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diesel_bill', models.FileField(blank=True, null=True, upload_to='settlement/diesel/')),
                ('cleaning_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grease_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grease_bill', models.FileField(blank=True, null=True, upload_to='settlement/grease/')),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='vouchers.holidaybooking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripSettlementCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='settlement/custom/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_charges', to='vouchers.tripsettlement')),
            ],
        ),
    ]
