# Generated by Django 5.2.7 on 2026-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0027_repair_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_functions',
            field=models.BooleanField(default=True, help_text='Enable Functions module for this company'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_holidays',
            field=models.BooleanField(default=True, help_text='Enable Holidays module for this company'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_vouchers',
            field=models.BooleanField(default=True, help_text='Enable Vouchers module for this company'),
        ),
    ]
