# Generated by Django 5.2.7 on 2026-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0028_company_module_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaybooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
