# Generated by Django 5.2.7 on 2026-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0030_repairmaintenance_km_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_enabled', models.BooleanField(default=True)),
                ('function_enabled', models.BooleanField(default=True)),
                ('holiday_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
            },
        ),
    ]
