# Generated by Django 5.2.7 on 2025-10-24 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='title',
        ),
        migrations.AddField(
            model_name='voucher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='voucher_attachments/'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='name_title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='pay_to',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('PETTY_CASH', 'Petty Cash')], default='CASH', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='vouchers.voucher')),
            ],
        ),
    ]
