# Generated by Django 5.2.7 on 2025-10-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_voucher_amount_remove_voucher_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='name_title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='pay_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(),
        ),
    ]
