# Generated by Django 5.2.7 on 2025-11-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_particular_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'permissions': (('can_approve_voucher', 'Can approve/reject vouchers'),)},
        ),
    ]
