# Generated by Django 5.2.7 on 2025-11-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucher_assigned_approver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='assigned_approver',
        ),
        migrations.AddField(
            model_name='voucher',
            name='assigned_approvers',
            field=models.ManyToManyField(blank=True, help_text='Admin Staff users who must approve this voucher', related_name='vouchers_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='vouchers.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'approver')},
            },
        ),
    ]
