# Generated by Django 5.2.7 on 2025-11-04 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['name'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterField(
            model_name='designation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
