# Generated by Django 5.2.7 on 2025-11-04 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_alter_designation_options_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='required_approvers',
            field=models.ManyToManyField(blank=True, help_text='All Admin Staff with designations', related_name='vouchers_to_approve_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoucherApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='vouchers.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'approver')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='vouchers_approved_multi', through='vouchers.VoucherApproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoucherRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_records', to='vouchers.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'rejector')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='rejections',
            field=models.ManyToManyField(blank=True, related_name='vouchers_rejected_multi', through='vouchers.VoucherRejection', to=settings.AUTH_USER_MODEL),
        ),
    ]
