# Generated by Django 5.2.7 on 2025-11-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_voucher_required_approvers_voucherapproval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='approvals',
        ),
        migrations.AlterUniqueTogether(
            name='voucherrejection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='voucherrejection',
            name='rejector',
        ),
        migrations.RemoveField(
            model_name='voucherrejection',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='rejections',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='required_approvers',
        ),
        migrations.DeleteModel(
            name='VoucherApproval',
        ),
        migrations.DeleteModel(
            name='VoucherRejection',
        ),
    ]
