# Generated by Django 5.2.7 on 2025-11-04 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_remove_voucher_approvals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='assigned_approver',
        ),
        migrations.AddField(
            model_name='voucher',
            name='approved_by_users',
            field=models.ManyToManyField(blank=True, help_text='Admin-Staff users that have approved this voucher', related_name='vouchers_fully_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
