# Generated by Django 5.2.7 on 2025-11-04 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0013_remove_voucher_assigned_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='approved_by_users',
        ),
        migrations.AddField(
            model_name='voucher',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, help_text='Admin Staff user assigned to approve this voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_to_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
