# Generated by Django 5.2.7 on 2025-11-04 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0014_remove_voucher_approved_by_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='approved_by',
        ),
        migrations.CreateModel(
            name='VoucherApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_approvals', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='vouchers.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'approver')},
            },
        ),
    ]
