# Generated by Django 5.2.7 on 2025-11-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0017_activeapprovaldesignation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='attachment',
            field=models.FileField(upload_to='vouchers/attachments/'),
        ),
    ]
