# Generated by Django 5.2.7 on 2025-11-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0018_alter_voucher_options_alter_voucher_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/attachments/'),
        ),
    ]
