# Generated by Django 5.2.7 on 2025-11-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0019_alter_voucher_options_alter_voucher_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='particular',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach receipt/invoice for this item', null=True, upload_to='vouchers/particulars/'),
        ),
    ]
