# Generated by Django 5.2.7 on 2025-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0020_particular_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Required only for Cheque payments', max_length=20, null=True),
        ),
    ]
