# Generated by Django 5.2.7 on 2025-11-06 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0021_voucher_cheque_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Lower number = earlier in approval chain', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active levels require approval')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vouchers.designation')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ActiveApprovalDesignation',
        ),
    ]
