# Generated by Django 5.2.7 on 2025-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0022_approvallevel_delete_activeapprovaldesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='required_approvers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='List of usernames required at voucher creation time'),
        ),
    ]
