# Generated by Django 5.2.7 on 2025-11-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0023_voucher_required_approvers_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherapproval',
            name='reason',
            field=models.TextField(blank=True, help_text='Required when status is REJECTED', null=True),
        ),
    ]
