# Generated by Django 5.2.7 on 2025-11-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0024_voucherapproval_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherapproval',
            name='reason',
        ),
    ]
