# Generated by Django 5.2.7 on 2025-11-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0025_remove_voucherapproval_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherapproval',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection. Required if status is REJECTED.', null=True),
        ),
    ]
