# Generated by Django 5.2.7 on 2025-11-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0026_voucherapproval_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherapproval',
            name='rejection_reason',
        ),
    ]
