# Generated by Django 5.2.7 on 2025-11-06 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0027_remove_voucherapproval_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallevel',
            options={'ordering': ['order'], 'verbose_name': 'Approval Level'},
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='particular',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/particulars/'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='required_approvers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Frozen list of usernames at creation time'),
        ),
    ]
