# Generated by Django 5.2.7 on 2025-11-06 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0028_alter_approvallevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallevel',
            options={'ordering': ['order'], 'verbose_name': 'Approval Level', 'verbose_name_plural': 'Approval Levels'},
        ),
        migrations.AddField(
            model_name='voucherapproval',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection. Required if status is REJECTED.', null=True),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active levels require approval'),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='order',
            field=models.PositiveIntegerField(help_text='Lower number = earlier in approval chain', unique=True),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='particular',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach receipt/invoice for this item', null=True, upload_to='vouchers/particulars/'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Required only for Cheque payments', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='required_approvers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='List of usernames required at voucher creation time'),
        ),
    ]
