# Generated by Django 5.2.7 on 2025-11-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0029_alter_approvallevel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherapproval',
            name='rejection_reason',
        ),
    ]
