# Generated by Django 5.2.7 on 2025-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0030_remove_voucherapproval_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='cheque_attachment',
            field=models.FileField(blank=True, help_text='Required only for Cheque payments', null=True, upload_to='vouchers/cheques/'),
        ),
    ]
