# Generated by Django 5.2.7 on 2025-11-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0031_voucher_cheque_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherapproval',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Required when status is REJECTED', null=True),
        ),
    ]
