# Generated by Django 5.2.7 on 2025-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0032_voucherapproval_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your digital signature (PNG/JPG, transparent background recommended)', null=True, upload_to='signatures/'),
        ),
    ]
