# Generated by Django 5.2.7 on 2025-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0033_userprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='account_details',
            field=models.CharField(blank=True, help_text='Selected account details (temporary text field)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque date (required for Cheque payments)', null=True),
        ),
    ]
