# Generated by Django 5.2.7 on 2025-11-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0034_voucher_account_details_voucher_cheque_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='account_details',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='cheque_date',
        ),
    ]
