# Generated by Django 5.2.7 on 2025-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0035_remove_voucher_account_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='account_details',
            field=models.CharField(blank=True, help_text='Account details for Cheque payments (will be dropdown later)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Date on the cheque - required for Cheque payments', null=True),
        ),
    ]
