# Generated by Django 5.2.7 on 2025-11-09 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0036_voucher_account_details_voucher_cheque_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bank_name'],
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
        migrations.AlterField(
            model_name='voucher',
            name='account_details',
            field=models.ForeignKey(blank=True, help_text='Bank account for Cheque payments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.accountdetail'),
        ),
    ]
