# Generated by Django 5.2.7 on 2025-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0037_accountdetail_alter_voucher_account_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='attachment',
            field=models.FileField(help_text='Attach receipt/invoice for this item - REQUIRED', upload_to='vouchers/particulars/'),
        ),
    ]
