# Generated by Django 5.2.7 on 2025-11-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0038_alter_particular_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=200)),
                ('gst_no', models.CharField(blank=True, help_text='GST Number (e.g., 22AAAAA0000A1Z5)', max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN Number (e.g., AAAAA0000A)', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Full company address', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='company/logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Detail',
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
