# Generated by Django 5.2.7 on 2025-11-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0039_companydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='email',
            field=models.EmailField(blank=True, help_text='Company email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='phone',
            field=models.CharField(blank=True, help_text='Company phone number', max_length=20, null=True),
        ),
    ]
