# Generated by Django 5.2.7 on 2025-11-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0040_companydetail_email_companydetail_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='cheque_attachment',
        ),
        migrations.CreateModel(
            name='ChequeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/cheques/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_attachments', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='MainAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/main/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_attachments', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ParticularAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/particulars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vouchers.particular')),
            ],
        ),
    ]
