# Generated by Django 5.2.7 on 2025-12-01 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0041_remove_particular_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='account_details',
        ),
        migrations.RemoveField(
            model_name='approvallevel',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='approvallevel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='chequeattachment',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='mainattachment',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='particularattachment',
            name='particular',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='cheque_date',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='required_approvers_snapshot',
        ),
        migrations.RemoveField(
            model_name='voucherapproval',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='particular',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach receipt/invoice for this item', null=True, upload_to='vouchers/particulars/'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/attachments/'),
        ),
        migrations.CreateModel(
            name='ActiveApprovalDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.designation', unique=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Approval Designation',
                'verbose_name_plural': 'Active Approval Designations',
            },
        ),
        migrations.DeleteModel(
            name='AccountDetail',
        ),
        migrations.DeleteModel(
            name='ApprovalLevel',
        ),
        migrations.DeleteModel(
            name='ChequeAttachment',
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
        migrations.DeleteModel(
            name='MainAttachment',
        ),
        migrations.DeleteModel(
            name='ParticularAttachment',
        ),
    ]
