# Generated by Django 5.2.7 on 2025-12-01 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0042_remove_voucher_account_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='attachment',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your digital signature (PNG/JPG, transparent background recommended)', null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Date on the cheque - required for Cheque payments', null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='required_approvers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='List of usernames required at voucher creation time'),
        ),
        migrations.AddField(
            model_name='voucherapproval',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Required when status is REJECTED', null=True),
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bank_name'],
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='account_details',
            field=models.ForeignKey(blank=True, help_text='Bank account for Cheque payments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.accountdetail'),
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Lower number = earlier in approval chain', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active levels require approval')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vouchers.designation')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChequeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/cheques/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_attachments', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=200)),
                ('gst_no', models.CharField(blank=True, help_text='GST Number (e.g., 22AAAAA0000A1Z5)', max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN Number (e.g., AAAAA0000A)', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Full company address', null=True)),
                ('email', models.EmailField(blank=True, help_text='Company email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Company phone number', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='company/logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Detail',
                'verbose_name_plural': 'Company Details',
            },
        ),
        migrations.CreateModel(
            name='MainAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/main/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_attachments', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ParticularAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/particulars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vouchers.particular')),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveApprovalDesignation',
        ),
    ]
